
version: 2

project_name: witr
builds:
  - id: witr
    main: ./cmd/witr
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X 'main.buildDate={{ .Date }}'
    env:
      - CGO_ENABLED=0
    binary: witr

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - docs/**
      - docs/witr.1
checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
  files:
    - "dist/*"

nfpms:
  - id: witr
    package_name: witr
    formats:
      - deb
      - rpm
    maintainer: Pranshu Parmar <pranshu.parmar@gmail.com>
    description: witr explains why a process or port is running by tracing its ancestry.
    homepage: https://github.com/pranshuparmar/witr
    license: Apache-2.0
    bindir: /usr/local/bin
    contents:
      - src: dist/witr_{{ .Os }}_{{ .Arch }}*/witr
        dst: /usr/local/bin/witr
        file_info:
          mode: 0755

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: pranshuparmar
    name: witr
